@startuml
title シーケンス図
ユーザ -> 鯖: リクエスト
鯖 --> 鯖:ファイル更新
鯖 -> DB鯖:更新
alt 更新成功
  DB鯖 --> 鯖:成功通知
  鯖 --> ユーザ:更新しましたわよ
else
  DB鯖 --> 鯖:失敗通知
  鯖 --> ユーザ:更新失敗しましたわよ
  loop 腹の虫が治るまで
    ユーザ -> 鯖:DOS攻撃
  end
end
@enduml